version: '3'
services:
  postgres:
    container_name: kangho_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: Kangho_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
  minio:
    image: docker.io/bitnami/minio:2022
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"